<?php


function ct_redirect_menu(){
    return array(
        'admin/config/search/ct-config-path' => array(
            'title'            => t('Manage settings for redirect'),
            'description'      => t('Configure basic settings for redirect'),
            'page callback'    => 'drupal_get_form',
            'page arguments'   => array('ct_redirect_admin_form'),
            'access arguments' => array('admin-redirect'),
            'file' => 'ct_redirect.admin.inc'
        ),
    );
}

/**
 * Implement hook_permission()
 */
function ct_redirect_permission() {
    return array(
        'admin-redirect' => array(
            'title'       => t("Redirect URLs"),
            'description' => t("Allow the user to create redirect urls")
        ),
    );
}
//function for redirection
function ct_urlRedirect($path){
	//arrangement with the urls for redirection, the key is redirected to the value
	$redirigir=array("urlorigen"=>"urldestino");

	//It looks for if the key is in the array
	if(array_key_exists($path,$redirigir)){
		//It is redirected to the value
		header ('location: '.$redirigir[$path]);
	}
}

//The event of the page is captured before loading and the search is executed
function ct_redirect_preprocess_page(&$vars) {
	ct_urlRedirect($_SERVER['REQUEST_URI']);
}