<?php

//función para redirección
function ct_urlRedirect($path){
	//arreglo con las url para redirección, el key se redirige al value
	$redirigir=array("urlorigen"=>"urldestino");

	//Se busca si el key está en el array
	if(array_key_exists($path,$redirigir)){
		//Se redirecciona al value
		//printVar($redirigir[$path],'Pa donde va');
		header ('location: '.$redirigir[$path]);
	}
}

//Se ccaptura el evento de la página antes de cargar y se ejecuta la busqueda
function ct_redirect_preprocess_page(&$vars) {
	//printVar($_SERVER['REQUEST_URI']);
	Brm_urlRedirect($_SERVER['REQUEST_URI']);
}